import Layouts from "@/components/Layouts";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lemon Hive Project",
  description: "Generated by Lemon Hive Project",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layouts>{children}</Layouts>
      </body>
    </html>
  );
}
